export enum GlobalEventName {
  ON_CONNECTED_WALLET = 'GLOBAL/ON_CONNECTED_WALLET',
  ON_DEPOSIT_CONFIRMATION = 'GLOBAL/ON_DEPOSIT_CONFIRMATION',
  ON_DEPOSIT_COMPLETED = 'GLOBAL/ON_DEPOSIT_COMPLETED'
}
