import Hanz from 'images/authors/hanz.jpg'
import Howater from 'images/authors/howater.png'
import Moffi from 'images/authors/moffi.jpg'
import PhatBear from 'images/authors/phat_bear.jpg'
import TienTranRB from 'images/authors/tien_tran_rb.jpg'
export const authorData = {
  en: [
    {
      name: 'Duy Hai Nguyen',
      nickname: 'Hanz',
      gender: 'Male',
      age: 29,
      avatar: Hanz,
      socialLink: {
        fb: 'https://www.facebook.com/duyhai.nguyen.336333/',
        be: 'https://www.behance.net/hanznguyen',
        ig: '',
      },
      bio: [
        'Interests: Watching movies, soccer, traveling, cuisine',
        'Comic drawing experience: Over 10 years',
        "Prominent created works/one-shots: The Stag and the Huntsman (3rd prize SMA 4), I'm always here (Honourable mention SMA Extra 1), Time Travel (2 chapters, monthly winner of Dream's World contest)",
        'Favorite comic genres: Shounen, Seinen, Sci-fi, Fantasy, Zombie',
        'Comic creation philosophy: Manga is Freedom',
      ],
    },
    {
      name: 'Hoa Minh Nguyen',
      nickname: 'Howater',
      avatar: Howater,
      gender: 'Male',
      age: 21,
      socialLink: {
        fb: 'https://www.facebook.com/Howaterr',
        be: '',
        ig: '',
      },
      bio: [
        'Interests: Pretending to be old?',
        'Comic drawing experience: Progressing through the years, started as early as 7 years old',
        "Created works/chapters: 3 stories, but they're all unfinished and stored away",
        'Favorite comic genres: Sennen, shounen, adventure, philosophy, psychology, comedy, etc',
        "Comic creation philosophy: Haven't really thought of anything serious, just a feeling that the story needs a perspective",
      ],
    },
    {
      name: 'Thanh Huong Bui',
      nickname: 'UMA',
      gender: 'Female',
      age: 33,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100034749499116',
        be: 'https://www.behance.net/buithanhhuong2811',
        ig: 'https://www.instagram.com/littleluciferinart/',
      },
      bio: [
        'Interests: Watching movies, reading books, sports',
        'Created works/chapters: None so far',
        'Favorite comic genres: Adventure, shounen, horror, detective',
        "Comic creation philosophy: If drawing for money, won't make it beautiful",
      ],
    },
    {
      name: 'Ngoc Cuong Nguyen',
      nickname: 'MOFFI',
      gender: 'Male',
      avatar: Moffi,
      age: 22,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100091931892797&show_switched_tooltip=false',
        be: '',
        ig: 'https://www.instagram.com/moffingoccuong/',
      },
      bio: [
        'Interests: Listening to music, sleeping',
        'Comic drawing experience: 1 year',
        'Created works/chapters: ultraV',
        'Favorite comic genres: Western comics.',
        'Comic creation philosophy: Satisfy the liberation of trapped images',
      ],
    },
    {
      name: 'Duc Phat Nguyen',
      nickname: 'PHAT BEAR',
      gender: 'Male',
      avatar: PhatBear,
      age: 25,
      socialLink: {
        fb: 'https://www.facebook.com/Nguyen.Duc.Phat.1998',
        be: '',
        ig: '',
      },
      bio: [
        'Interests: Oil painting, comic creation, film directing, screenwriting',
        'Comic drawing experience: 8 years since the first comic',
        'Created works/chapters: "The Informant."',
        'Favorite comic genres: Dark fantasy, horror.',
        'Comic creation philosophy: A good script is the core, good imagery is essential, and consistency is key',
      ],
    },
    {
      name: 'Thi Cam Tien Tran',
      nickname: 'TIEN TRAN RB',
      avatar: TienTranRB,
      gender: 'Female',
      age: 17,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100085164150318',
        be: '',
        ig: '',
      },
      bio: [
        'Interests: Drawing, dancing, volleyball, listening to music, traveling',
        'Comic drawing experience: Over 10 years.',
        'Created works/chapters: "Ghi nhớ" (Remember)',
        'Favorite comic genres: Psychological, shoujo, adventure, one shot',
        'Comic creation philosophy: Creating out of passion, for the sake of art',
      ],
    },
  ],
  vn: [
    {
      name: 'Nguyễn Duy Hải',
      nickname: 'Hanz',
      gender: 'Male',
      avatar: Hanz,
      age: 29,
      socialLink: {
        fb: 'https://www.facebook.com/duyhai.nguyen.336333/',
        be: 'https://www.behance.net/hanznguyen',
        ig: '',
      },
      bio: [
        'Sở thích: Xem phim, bóng đá, du lịch, ẩm thực',
        'Kinh nghiệm vẽ truyện tranh: Hơn 10 năm',
        'Các đầu truyện/one-shot từng sáng tác nổi bật: The Stag and the Huntsman (3rd prize SMA 4), I’m always here (Honourable mention SMA Extra 1), Time Travel (2 chapter, monthly winner of Dream’s World contest) ',
        'Thể loại truyện tranh yêu thích: Shounen, Seinen, Sci-fi, Fantasy, Zombie',
        'Phương châm sáng tác truyện tranh: Manga is Freedom',
      ],
    },
    {
      name: 'Nguyễn Hòa Minh',
      nickname: 'Howater',
      gender: 'Male',
      avatar: Howater,
      age: 21,
      socialLink: {
        fb: 'https://www.facebook.com/Howaterr',
        be: '',
        ig: '',
      },
      bio: [
        'Sở thích: Làm người già?',
        'Kinh nghiệm vẽ truyện tranh: Chấp vá qua từng năm, sớm nhất là 7 tuổi.',
        'Các đầu truyện/chap truyện từng sáng tác: 3 truyện nhưng dang dở và bị xếp vô kho',
        'Thể loại truyện tranh yêu thích: Sennen, shounen, adventure, philosophy, psychology, comedy...vv',
        'Phương châm sáng tác truyện tranh: Chưa nghĩ ra gì nghiêm túc lắm, chỉ là có cảm giác câu chuyện đó cần được điểm nhìn)',
      ],
    },
    {
      name: 'Bùi Thanh Hương',
      nickname: 'UMA',
      gender: 'Female',
      age: 33,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100034749499116',
        be: 'https://www.behance.net/buithanhhuong2811',
        ig: 'https://www.instagram.com/littleluciferinart/',
      },
      bio: [
        'Sở thích : xem phim, đọc sách, thể thao',
        'Các đầu truyện/ chap truyện từng sáng tác:',
        'Thể loại truyện tranh yêu thích: adventure, shounen, horror, detective',
        'Phương châm sáng tác truyện tranh: vẽ vì tiền thì không vẽ đẹp được',
      ],
    },
    {
      name: 'Huỳnh Ngọc Cường',
      nickname: 'MOFFI',
      gender: 'Male',
      avatar: Moffi,
      age: 22,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100091931892797&show_switched_tooltip=false',
        be: '',
        ig: 'https://www.instagram.com/moffingoccuong/',
      },
      bio: [
        'Sở thích: nghe nhạc, ngủ',
        'Kinh nghiệm vẽ truyện tranh: 1 năm',
        'Các đầu truyện/ chap truyện từng sáng tác UltraV',
        'Thể loại truyện tranh yêu thích: comic phương tây',
        'Phương châm sáng tác truyện tranh: Thỏa mãn việc giải phóng hình ảnh bị mắc kẹt trong đầu',
      ],
    },
    {
      name: 'Nguyễn Đức Phát',
      nickname: 'PHAT BEAR',
      gender: 'Male',
      avatar: PhatBear,
      age: 25,
      socialLink: {
        fb: 'https://www.facebook.com/Nguyen.Duc.Phat.1998',
        be: '',
        ig: '',
      },
      bio: [
        'Sở thích: sáng tác sơn dầu, truyện tranh, đạo diễn phim, biên kịch',
        'Kinh nghiệm vẽ truyện tranh: 8 năm kể từ truyện đầu tay',
        'Các đầu truyện/ chap truyện từng sáng tác: người báo ',
        'Thể loại truyện tranh yêu thích: Dark fantsy, horror',
        'Phương châm sáng tác truyện tranh: kịch bản tốt là cốt lõi, hình ảnh tốt là bắt buộc, chậm chắc',
      ],
    },
    {
      name: 'Trần Thị Cẩm Tiên',
      nickname: 'TIÊN TRẦN RB',
      avatar: TienTranRB,
      gender: 'Female',
      age: 17,
      socialLink: {
        fb: 'https://www.facebook.com/profile.php?id=100085164150318',
        be: '',
        ig: '',
      },
      bio: [
        'Sở thích: vẽ, nhảy, bóng chuyền, nghe nhạc, đi phượt.',
        'Kinh nghiệm vẽ truyện tranh:hHơn 10 năm',
        'Các đầu truyện/ chap truyện từng sáng tác: Ghi nhớ.',
        'Thể loại truyện tranh yêu thích: Psychological, shoujo, adventure, one shot.',
        'Phương châm sáng tác truyện tranh: Làm vì đam mê, vì nghệ thuật',
      ],
    },
  ],
}
