name: Main CI
on:
  workflow_dispatch:
    branches:
      - main
    permissions:
      users:
        - harisato
    inputs:
      version:
        type: string
        description: Release version
        required: true
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/punkga-homepage:${{ inputs.version }}_${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ env.CONTAINER_RELEASE_IMAGE }}
  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/punkga-homepage:${{ inputs.version }}_${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops-prod >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops-prod.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-xstaxy/punkga >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_punkga_homepage >> $GITHUB_ENV
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          chmod 777 -R ./ci
          ./ci/updateManifest.sh
